---
title: "Suivi des enquêteurs par zone de travail"
output:
  html_document: default
  html_notebook: default
---
Ce document permet de suivre l’avancée de l’enquête.

```{r}
library("leaflet")
library("rgdal")
library("maptools")
library("sp")
library("stringr")
library("rgeos")
#library("OpenStreetMap")
library("ggmap")
#configuration du dossier par défaut
setwd("~/Documents/jftardieu/enquete_grandsud/")

enquete <- read.csv("~/Documents/jftardieu/enquete_grandsud/enquete170517_1253_retravaille.csv")
zones <- readShapePoly("~/Documents/jftardieu/zones_enquete/enquete_zone84/zones_enquete84.shp")
zones$travail <- tolower(zones$Code_enque) #code enqueteur en minuscules
CRSojb <- CRS("+proj=longlat +datum=WGS84 +no_defs") #scr de référence
#enqueteur@proj4string <- CRSojb 
zones_trav@proj4string <- CRSojb
coordinates(enqueteur) <- ~ code_gps.Longitude + code_gps.Latitude 
#définition coordonnées « enqueteur »
proj4string(enqueteur) <- proj4string(zones_trav) #mise en place scr identique deux jeux données
```

# Sud
## Sd001
```{r}

enqueteur <- enquete[enquete$zone_travail == "sd001",]
zones_trav <- zones[zones$travail == "sd001",] #filtre par zone d’enquete

#point dans polygone
over(enqueteur, zones_trav)
#nbre points dans polygones

# carte point dans polygone
plot(zones_trav)
points(enqueteur$code_gps.Latitude ~ enqueteur$code_gps.Longitude, col = "red", cex = 1)
```




Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).
